version: '3'
services:

    flaskapp1:
        build: ./flaskapp1
        ports:
            - "5001:5000"
    flaskapp2:
        build: ./flaskapp2
        ports:
            - "5002:5000"

    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
           - flaskapp1
           - flaskapp2

networks:
    default:
        external:
            name: distNet