version: '3'
services:

    aioapp1:
        build: ./aioapp1
        ports:
            - "5001:5000"
    aioapp2:
        build: ./aioapp2
        ports:
            - "5002:5000"

    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
           - aioapp1
           - aioapp2

networks:
    default:
        external:
            name: distNet