version: '3'
services:

    aioapp1:
        build: ./aioapp1
        ports:
            - "5001:5000"
        env_file: ./aws.env
        restart: always

    aioapp2:
        build: ./aioapp2
        ports:
            - "5002:5000"
        env_file: ./aws.env
        restart: always

    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
           - aioapp1
           - aioapp2
        restart: always

networks:
    default:
        external:
            name: distNet
